### ISSUE TITLE
Softether + DNSMasq

### ISSUE THREAD

**Issue by jibeex** [combro2k/dockerfiles#1]
Hello Combro2k,

Thank you for your work on Docker-softether.
https://github.com/combro2k/docker-softether

I am trying to use Softether + DNSMasq inside a docker container. But I didn't succeed.  They are working fine without Docker.
Could you please explain in more details how to use your docker image to make it work or which methods you are using ?
Thank you in advance.

best regards,
Jianbin

**Comment by combro2k** [comment]
Hi @jibeex 

Depends, I had it working before all the network docker extensions, never tried after it
to use tap devices you need the NET_ADMIN cap (--cap-add=NET_ADMIN)
or you can run it as privileged (not recommended).

see more here https://www.reddit.com/r/docker/comments/4cw758/accessing_tuntap_device_inside_of_a_docker/

I will soon finish my alpine softether to replace openvpn-as server, cause I changed from iptables to nftables, openvpn-as requires iptables ... stupid (!).

Anyway, if you can not get it working if you can wait for a few days or so wait on my alpine softether container.

**Comment by jibeex** [comment]
Hi Combro2k, 

I have added the parameter (--cap-add=NET_ADMIN), but when I create a tap device in Softether, the status of the tap appears always as "error".

**Comment by combro2k** [comment]
@jibeex 
Here I can create an tap device locally at docker
It shows itself when I type `ip a`
There is however not yet any IP configuration, thats pretty normal

**Comment by jibeex** [comment]
I cannot see that in the results from `ip a`. And when I check on Softether, the status of the tap is `error`. 
`uname -a
Linux localhost 4.4.0-89-generic #112-Ubuntu SMP Mon Jul 31 19:38:41 UTC 2017 x86_64 GNU/Linux`


```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether f2:3c:91:d4:5d:16 brd ff:ff:ff:ff:ff:ff
    inet 172.104.xxx.xxx/24 brd 172.104.73.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 2400:8902::f03c:91ff:xxxx:xxxx/64 scope global mngtmpaddr dynamic
       valid_lft 2591998sec preferred_lft 604798sec
    inet6 fe80::f03c:91ff:fed4:5d16/64 scope link
       valid_lft forever preferred_lft forever
3: docker0: <NO-CARRIER,BROADCAST,MULTICAST,PROMISC,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:ef:3e:21:xx brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
```

**Comment by combro2k** [comment]
Which version of Ubuntu are you running?

**Comment by combro2k** [comment]
No reply anymore, suggests he gave up or succeeded
