### ISSUE TITLE
SSH suddenly logging me off immediately

### ISSUE THREAD

**Issue by bmmiller** [combro2k/dockerfiles#3]
Not sure what happened but after one of the recent pushes, this is completely broken for me now.  When I attempt to SSH in, it succeeds and then immediately disconnects.  Trying to SSH in via Putty from Windows, same as always.  Logs don't seem to provide much information:

![image](https://user-images.githubusercontent.com/1325775/57748871-605c8880-76a1-11e9-86da-443ff2740f29.png)

Any idea what could have caused this changed behavior?

**Comment by combro2k** [comment]
hmm weird, locale error:

panic: locale.c: 893: Unexpected character in locale name '2E.
Will have a look ;-)

**Comment by combro2k** [comment]
Fix is pushed.
If you can't wait replace /etc/profile.d/tmux.sh with:

if test $TMUX; then
	LC_ALL=c exec /usr/bin/weechat 
elif tmux has-session -t WeeChat 2>/dev/null; then
	tmux attach -t WeeChat
	exit
else
	tmux new -s WeeChat
	exit
fi

Ref: https://raw.githubusercontent.com/combro2k/dockerfiles/master/alpine-weechat/resources/etc/profile.d/tmux.sh

**Comment by bmmiller** [comment]
Perfect.  Works great now.  Thanks!
